/* Concatenate src/* into a single self-contained index.html,
   plus robots.txt and sitemap.xml for the repo root. */
const fs = require("fs");
const path = require("path");
const { SITE, AUTHOR, GA_ID, TITLE } = require("./site.config");
const { loadSrc } = require("./srcload");

const root = __dirname;
const read = (p) => fs.readFileSync(path.join(root, p), "utf8");
const esc = (s) => String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

/* pull TOPICS / QUESTIONS out of the source so the static content can't drift */
const { TOPICS, QUESTIONS } = loadSrc(["src/topics.js", "src/questions.js"], ["TOPICS", "QUESTIONS"]);
const NQ = QUESTIONS.length;
const NT = TOPICS.length;

const DESC = `Practise MongoDB free: ${NQ} query exercises across ${NT} topics, with cheatsheets and a live runner that checks your answer. No signup, runs in your browser.`;
const DESC_LONG = `Free MongoDB practice: ${NQ} hands-on query exercises across ${NT} topics, with per-topic cheatsheets and a live query runner. Write real find() and aggregate() queries, run them instantly, and get your answer checked. No signup, no server, works offline.`;

/* mingo is vendored in vendor/ so `node build.js` needs no npm install.
   Refresh it with: npm run update-mingo */
const mingoJs = read("vendor/mingo.min.js");
const css = read("src/styles.css");
const js = [
  "src/analytics.js",
  "src/data.js",
  "src/topics.js",
  "src/master.js",
  "src/questions.js",
  "src/engine.js",
  "src/editor.js",
  "src/app.js"
].map((f) => "/* ===== " + path.basename(f) + " ===== */\n" + read(f)).join("\n\n");

/* Crawlers that do not run JavaScript would otherwise see an empty <main>.
   The app replaces this on first render. */
const boot = `<div class="wrap">
      <h1>MongoQuest – practise MongoDB queries in your browser</h1>
      <p class="sub">${NQ} hands-on exercises across ${NT} topics, a cheatsheet for each one, and a query runner that checks your answer. Everything runs locally in your browser.</p>
      <h2>Topics covered</h2>
      <ul>
${TOPICS.map((t) => `        <li><b>${esc(t.name)}</b> – ${esc(t.blurb)}</li>`).join("\n")}
      </ul>
      <noscript><p><b>MongoQuest needs JavaScript</b> – the query engine runs entirely in your browser, so there is no server to fall back to.</p></noscript>
    </div>`;

const jsonLd = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "SoftwareApplication",
      "name": "MongoQuest",
      "url": SITE,
      "description": DESC_LONG,
      "applicationCategory": "EducationalApplication",
      "applicationSubCategory": "Programming practice",
      "operatingSystem": "Any (web browser)",
      "browserRequirements": "Requires JavaScript",
      "isAccessibleForFree": true,
      "offers": { "@type": "Offer", "price": "0", "priceCurrency": "USD" },
      "keywords": "MongoDB, MongoDB practice, MongoDB exercises, aggregation pipeline, mongo shell, NoSQL, query practice",
      "author": { "@id": SITE + "#author" },
      "creator": { "@id": SITE + "#author" }
    },
    {
      "@type": "Person",
      "@id": SITE + "#author",
      "name": AUTHOR.name,
      "url": AUTHOR.linkedin,
      "sameAs": [AUTHOR.linkedin],
      "jobTitle": "Software Developer"
    },
    {
      "@type": "LearningResource",
      "name": "MongoDB query exercises",
      "url": SITE,
      "learningResourceType": "Practice problem set",
      "educationalLevel": "Beginner to intermediate",
      "teaches": TOPICS.map((t) => t.name),
      "isAccessibleForFree": true,
      "inLanguage": "en"
    }
  ]
};

const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<!-- Generated by build.js – edit site.config.js instead. -->
<script>
var GA_ID = ${JSON.stringify(GA_ID)};
var AUTHOR = ${JSON.stringify(AUTHOR)};
</script>

<title>${esc(TITLE)}</title>
<meta name="description" content="${esc(DESC)}">
<meta name="keywords" content="MongoDB practice, MongoDB exercises, MongoDB queries online, learn MongoDB, aggregation pipeline practice, mongo shell practice, NoSQL exercises, MongoDB interview questions, $lookup, $unwind, $group">
<meta name="author" content="${esc(AUTHOR.name)}">
<meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1">
<meta name="theme-color" content="#0e1116">
<meta name="color-scheme" content="dark">
<link rel="canonical" href="${SITE}">

<meta property="og:type" content="website">
<meta property="og:site_name" content="MongoQuest">
<meta property="og:title" content="${esc(TITLE)}">
<meta property="og:description" content="${esc(DESC_LONG)}">
<meta property="og:url" content="${SITE}">
<meta property="og:locale" content="en_US">
<meta property="og:image" content="${SITE}og.png">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta property="og:image:alt" content="MongoQuest – ${NQ} MongoDB query exercises with a live runner">

<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="${esc(TITLE)}">
<meta name="twitter:description" content="${esc(DESC_LONG)}">
<meta name="twitter:image" content="${SITE}og.png">

<script type="application/ld+json">
${JSON.stringify(jsonLd, null, 2)}
</script>

<link rel="icon" href="data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><text y='.9em' font-size='90'>🍃</text></svg>">
<style>
${css}
</style>
</head>
<body>
<div class="app">
  <header>
    <button class="btn sm menu-btn" id="menu">☰</button>
    <div class="brand"><span class="leaf">🍃</span><span class="name">MongoQuest</span><small>practise MongoDB queries</small></div>
    <div class="head-right">
      <div class="overall"><span id="otxt">0 / 0</span><span class="bar"><i id="obar" style="width:0%"></i></span></div>
    </div>
  </header>
  <aside id="side"></aside>
  <main id="main">${boot}</main>
</div>
<div class="scrim" id="scrim"></div>
<div class="toast" id="toast"></div>

<script>
/* ===== mingo (MIT), bundled so this file works offline ===== */
${mingoJs}
</script>
<script>
${js}
</script>
</body>
</html>
`;

fs.writeFileSync(path.join(root, "index.html"), html);

fs.writeFileSync(path.join(root, "robots.txt"),
  "User-agent: *\nAllow: /\n\nSitemap: " + SITE + "sitemap.xml\n");

fs.writeFileSync(path.join(root, "sitemap.xml"),
  '<?xml version="1.0" encoding="UTF-8"?>\n' +
  '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' +
  '  <url>\n    <loc>' + SITE + '</loc>\n    <changefreq>monthly</changefreq>\n    <priority>1.0</priority>\n  </url>\n' +
  '</urlset>\n');

console.log("index.html", (Buffer.byteLength(html) / 1024).toFixed(0) + " KB");
console.log("robots.txt, sitemap.xml");
if (SITE.indexOf("YOUR-GITHUB-USERNAME") >= 0) {
  console.log("\n!! SITE is still a placeholder – set it in site.config.js before deploying.");
}
