/* MongoQuest sample datasets. Keep them small enough to eyeball. */
const DATASETS = {

  restaurants: [
    { _id: 1, name: "Bombay Spice House", borough: "Manhattan", cuisine: "Indian", price: 3, seats: 60, isOpen: true,
      address: { building: "412", street: "Lexington Ave", zipcode: "10017", coord: [-73.9754, 40.7512] },
      grades: [ { date: new Date("2023-11-02"), grade: "A", score: 9 }, { date: new Date("2023-04-18"), grade: "A", score: 11 }, { date: new Date("2022-09-30"), grade: "B", score: 18 } ] },
    { _id: 2, name: "Nonna's Kitchen", borough: "Brooklyn", cuisine: "Italian", price: 2, seats: 40, isOpen: true,
      address: { building: "77", street: "Bedford Ave", zipcode: "11211", coord: [-73.9571, 40.7143] },
      grades: [ { date: new Date("2023-10-11"), grade: "A", score: 7 }, { date: new Date("2023-02-27"), grade: "A", score: 10 } ] },
    { _id: 3, name: "Golden Dragon", borough: "Queens", cuisine: "Chinese", price: 1, seats: 90, isOpen: true,
      address: { building: "13", street: "Main St", zipcode: "11354", coord: [-73.8302, 40.7601] },
      grades: [ { date: new Date("2023-12-05"), grade: "C", score: 32 }, { date: new Date("2023-06-14"), grade: "B", score: 21 }, { date: new Date("2022-11-19"), grade: "A", score: 12 } ] },
    { _id: 4, name: "Le Petit Jardin", borough: "Manhattan", cuisine: "French", price: 4, seats: 32, isOpen: true,
      address: { building: "205", street: "Bleecker St", zipcode: "10012", coord: [-74.0021, 40.7301] },
      grades: [ { date: new Date("2024-01-09"), grade: "A", score: 5 }, { date: new Date("2023-05-22"), grade: "A", score: 8 } ] },
    { _id: 5, name: "Taco Riot", borough: "Bronx", cuisine: "Mexican", price: 1, seats: 24, isOpen: false,
      address: { building: "890", street: "Grand Concourse", zipcode: "10451", coord: [-73.9229, 40.8199] },
      grades: [ { date: new Date("2023-08-30"), grade: "B", score: 19 }, { date: new Date("2023-01-15"), grade: "C", score: 28 } ] },
    { _id: 6, name: "Sakura Omakase", borough: "Manhattan", cuisine: "Japanese", price: 4, seats: 16, isOpen: true,
      address: { building: "31", street: "W 8th St", zipcode: "10011", coord: [-73.9968, 40.7328] },
      grades: [ { date: new Date("2024-02-01"), grade: "A", score: 3 }, { date: new Date("2023-07-07"), grade: "A", score: 6 } ] },
    { _id: 7, name: "Brooklyn Bagel Bar", borough: "Brooklyn", cuisine: "Bakery", price: 1, seats: 12, isOpen: true,
      address: { building: "9", street: "Court St", zipcode: "11201", coord: [-73.9903, 40.6924] },
      grades: [ { date: new Date("2023-09-21"), grade: "A", score: 13 } ] },
    { _id: 8, name: "Athena Taverna", borough: "Queens", cuisine: "Greek", price: 2, seats: 55, isOpen: true,
      address: { building: "2501", street: "Ditmars Blvd", zipcode: "11105", coord: [-73.9061, 40.7752] },
      grades: [ { date: new Date("2023-11-28"), grade: "A", score: 10 }, { date: new Date("2023-03-03"), grade: "B", score: 20 } ] },
    { _id: 9, name: "Seoul Fire BBQ", borough: "Manhattan", cuisine: "Korean", price: 3, seats: 70, isOpen: true,
      address: { building: "36", street: "W 32nd St", zipcode: "10001", coord: [-73.9873, 40.7478] },
      grades: [ { date: new Date("2024-01-25"), grade: "A", score: 9 }, { date: new Date("2023-06-02"), grade: "A", score: 14 }, { date: new Date("2022-12-12"), grade: "B", score: 22 } ] },
    { _id: 10, name: "Staten Slice Co", borough: "Staten Island", cuisine: "Pizza", price: 1, seats: 28, isOpen: true,
      address: { building: "144", street: "Bay St", zipcode: "10301", coord: [-74.0763, 40.6404] },
      grades: [ { date: new Date("2023-10-04"), grade: "B", score: 17 } ] },
    { _id: 11, name: "Curry Leaf Express", borough: "Queens", cuisine: "Indian", price: 1, seats: 20, isOpen: true,
      address: { building: "7402", street: "37th Ave", zipcode: "11372", coord: [-73.8896, 40.7489] },
      grades: [ { date: new Date("2023-12-19"), grade: "A", score: 11 }, { date: new Date("2023-05-05"), grade: "C", score: 30 } ] },
    { _id: 12, name: "The Rusty Anchor", borough: "Brooklyn", cuisine: "Seafood", price: 3, seats: 48, isOpen: false,
      address: { building: "18", street: "Van Brunt St", zipcode: "11231", coord: [-74.0117, 40.6785] },
      grades: [ { date: new Date("2023-07-30"), grade: "B", score: 16 }, { date: new Date("2022-10-08"), grade: "A", score: 12 } ] },
    { _id: 13, name: "Casa Del Sol", borough: "Bronx", cuisine: "Mexican", price: 2, seats: 44, isOpen: true,
      address: { building: "1150", street: "Southern Blvd", zipcode: "10459", coord: [-73.8892, 40.8261] },
      grades: [ { date: new Date("2024-02-14"), grade: "A", score: 8 }, { date: new Date("2023-08-08"), grade: "A", score: 13 } ] },
    { _id: 14, name: "Pho 88", borough: "Brooklyn", cuisine: "Vietnamese", price: 1, seats: 36, isOpen: true,
      address: { building: "88", street: "8th Ave", zipcode: "11220", coord: [-74.0021, 40.6413] },
      grades: [ { date: new Date("2023-11-11"), grade: "A", score: 12 }, { date: new Date("2023-04-04"), grade: "B", score: 19 } ] },
    { _id: 15, name: "Harlem Soul Table", borough: "Manhattan", cuisine: "American", price: 2, seats: 65, isOpen: true,
      address: { building: "2320", street: "Frederick Douglass Blvd", zipcode: "10027", coord: [-73.9524, 40.8103] },
      grades: [ { date: new Date("2023-09-09"), grade: "A", score: 6 }, { date: new Date("2023-01-30"), grade: "A", score: 9 }, { date: new Date("2022-08-16"), grade: "A", score: 11 } ] },
    { _id: 16, name: "Kebab Corner", borough: "Queens", cuisine: "Turkish", price: 1, seats: 18, isOpen: true,
      address: { building: "3011", street: "Steinway St", zipcode: "11103", coord: [-73.9159, 40.7627] },
      grades: [ { date: new Date("2023-10-26"), grade: "B", score: 20 } ] },
    { _id: 17, name: "Blue Hill Bistro", borough: "Manhattan", cuisine: "French", price: 4, seats: 38, isOpen: true,
      address: { building: "75", street: "Washington Pl", zipcode: "10011", coord: [-73.9989, 40.7318] },
      grades: [ { date: new Date("2024-03-01"), grade: "A", score: 4 } ] },
    { _id: 18, name: "Dim Sum Palace", borough: "Manhattan", cuisine: "Chinese", price: 2, seats: 120, isOpen: true,
      address: { building: "59", street: "Canal St", zipcode: "10002", coord: [-73.9931, 40.7148] },
      grades: [ { date: new Date("2023-12-28"), grade: "B", score: 18 }, { date: new Date("2023-05-17"), grade: "A", score: 10 }, { date: new Date("2022-11-02"), grade: "C", score: 27 } ] },
    { _id: 19, name: "Bronx Brick Oven", borough: "Bronx", cuisine: "Pizza", price: 2, seats: 50, isOpen: true,
      address: { building: "620", street: "Arthur Ave", zipcode: "10458", coord: [-73.8859, 40.8541] },
      grades: [ { date: new Date("2023-08-22"), grade: "A", score: 7 }, { date: new Date("2023-02-13"), grade: "A", score: 12 } ] },
    { _id: 20, name: "Island Jerk Hut", borough: "Brooklyn", cuisine: "Caribbean", price: 1, seats: 22, isOpen: true,
      address: { building: "1044", street: "Nostrand Ave", zipcode: "11225", coord: [-73.9494, 40.6591] },
      grades: [ { date: new Date("2023-11-15"), grade: "C", score: 33 }, { date: new Date("2023-03-20"), grade: "B", score: 21 } ] },
    { _id: 21, name: "Vegan Root", borough: "Manhattan", cuisine: "Vegetarian", price: 3, seats: 30, isOpen: true,
      address: { building: "101", street: "E 4th St", zipcode: "10003", coord: [-73.9885, 40.7261] },
      grades: [ { date: new Date("2024-01-17"), grade: "A", score: 5 }, { date: new Date("2023-06-27"), grade: "A", score: 8 } ] },
    { _id: 22, name: "Queens Diner", borough: "Queens", cuisine: "American", price: 1, seats: 80, isOpen: true,
      address: { building: "4110", street: "Queens Blvd", zipcode: "11104", coord: [-73.9224, 40.7443] },
      grades: [ { date: new Date("2023-09-14"), grade: "B", score: 22 }, { date: new Date("2023-01-08"), grade: "B", score: 19 } ] },
    { _id: 23, name: "Tandoor Nights", borough: "Brooklyn", cuisine: "Indian", price: 2, seats: 46, isOpen: true,
      address: { building: "301", street: "Church Ave", zipcode: "11218", coord: [-73.9764, 40.6449] },
      grades: [ { date: new Date("2023-12-01"), grade: "A", score: 9 } ] },
    { _id: 24, name: "Little Havana Cafe", borough: "Staten Island", cuisine: "Cuban", price: 2, seats: 34, isOpen: false,
      address: { building: "56", street: "Richmond Ave", zipcode: "10302", coord: [-74.1502, 40.6301] },
      grades: [ { date: new Date("2023-07-19"), grade: "A", score: 14 }, { date: new Date("2022-12-21"), grade: "B", score: 23 } ] }
  ],

  movies: [
    { _id: 101, title: "The Silent Harbor", year: 2016, rated: "PG-13", runtime: 118, genres: ["Drama", "Thriller"],
      directors: ["Ana Roth"], cast: ["Liam Vance", "Priya Nair", "Tom Okafor"], languages: ["English"],
      countries: ["USA"], imdb: { rating: 7.4, votes: 88210 }, awards: { wins: 3, nominations: 11 }, budgetM: 42 },
    { _id: 102, title: "Neon Circuit", year: 2019, rated: "R", runtime: 134, genres: ["Sci-Fi", "Action"],
      directors: ["Kenji Mori"], cast: ["Ada Blake", "Liam Vance"], languages: ["English", "Japanese"],
      countries: ["USA", "Japan"], imdb: { rating: 8.1, votes: 402300 }, awards: { wins: 7, nominations: 21 }, budgetM: 160 },
    { _id: 103, title: "Paper Lanterns", year: 2013, rated: "PG", runtime: 96, genres: ["Drama", "Family"],
      directors: ["Mei Chen", "Ana Roth"], cast: ["Priya Nair", "Sofia Ruiz"], languages: ["Mandarin", "English"],
      countries: ["China"], imdb: { rating: 7.9, votes: 51200 }, awards: { wins: 12, nominations: 18 }, budgetM: 8 },
    { _id: 104, title: "Dust and Iron", year: 2021, rated: "R", runtime: 152, genres: ["Western", "Drama"],
      directors: ["Hank Delgado"], cast: ["Tom Okafor", "Ada Blake", "Marcus Vale"], languages: ["English", "Spanish"],
      countries: ["USA", "Mexico"], imdb: { rating: 6.8, votes: 121400 }, awards: { wins: 1, nominations: 4 }, budgetM: 75 },
    { _id: 105, title: "The Cartographer", year: 2009, rated: "PG-13", runtime: 108, genres: ["Adventure", "Drama"],
      directors: ["Ana Roth"], cast: ["Liam Vance", "Sofia Ruiz"], languages: ["English", "French"],
      countries: ["UK", "France"], imdb: { rating: 7.1, votes: 63900 }, awards: { wins: 2, nominations: 6 }, budgetM: 30 },
    { _id: 106, title: "Glass Orchard", year: 2022, rated: "PG", runtime: 89, genres: ["Animation", "Family", "Adventure"],
      directors: ["Mei Chen"], cast: ["Priya Nair"], languages: ["English"],
      countries: ["USA"], imdb: { rating: 8.4, votes: 210500 }, awards: { wins: 9, nominations: 14 }, budgetM: 95 },
    { _id: 107, title: "Hollow Signal", year: 2018, rated: "R", runtime: 127, genres: ["Horror", "Thriller"],
      directors: ["Nadia Farouk"], cast: ["Marcus Vale", "Ada Blake"], languages: ["English"],
      countries: ["USA"], imdb: { rating: 6.2, votes: 44100 }, awards: { wins: 0, nominations: 2 }, budgetM: 12 },
    { _id: 108, title: "Winter Sonata Blue", year: 2015, rated: "PG-13", runtime: 141, genres: ["Romance", "Drama"],
      directors: ["Kenji Mori", "Mei Chen"], cast: ["Sofia Ruiz", "Tom Okafor", "Priya Nair"], languages: ["Korean", "English"],
      countries: ["South Korea"], imdb: { rating: 7.7, votes: 97800 }, awards: { wins: 5, nominations: 9 }, budgetM: 22 },
    { _id: 109, title: "Fault Lines", year: 2024, rated: "R", runtime: 113, genres: ["Thriller", "Crime"],
      directors: ["Hank Delgado", "Nadia Farouk"], cast: ["Ada Blake", "Marcus Vale", "Liam Vance"], languages: ["English"],
      countries: ["USA", "Canada"], imdb: { rating: 7.2, votes: 30250 }, awards: { wins: 1, nominations: 3 }, budgetM: 48 },
    { _id: 110, title: "The Beekeeper's Almanac", year: 2011, rated: "G", runtime: 84, genres: ["Documentary"],
      directors: ["Nadia Farouk"], cast: [], languages: ["English"],
      countries: ["UK"], imdb: { rating: 8.0, votes: 12100 }, awards: { wins: 4, nominations: 5 }, budgetM: 2 },
    { _id: 111, title: "Crimson Alley", year: 2020, rated: "R", runtime: 99, genres: ["Crime", "Action", "Thriller"],
      directors: ["Kenji Mori"], cast: ["Marcus Vale", "Sofia Ruiz"], languages: ["English", "Japanese"],
      countries: ["Japan"], imdb: { rating: 6.9, votes: 76400 }, awards: { wins: 2, nominations: 8 }, budgetM: 55 },
    { _id: 112, title: "Salt of the Steppe", year: 2007, rated: "PG-13", runtime: 165, genres: ["Drama", "History"],
      directors: ["Ana Roth", "Hank Delgado"], cast: ["Tom Okafor", "Priya Nair"], languages: ["Russian", "English"],
      countries: ["Russia", "Germany"], imdb: { rating: 7.6, votes: 28900 }, awards: { wins: 6, nominations: 10 }, budgetM: 18 },
    { _id: 113, title: "Zero Gravity Diner", year: 2023, rated: "PG", runtime: 92, genres: ["Comedy", "Sci-Fi"],
      directors: ["Mei Chen"], cast: ["Liam Vance", "Ada Blake", "Sofia Ruiz"], languages: ["English"],
      countries: ["USA"], imdb: { rating: 6.5, votes: 18700 }, awards: { wins: 0, nominations: 1 }, budgetM: 35 },
    { _id: 114, title: "Ashes of Tuesday", year: 2017, rated: "R", runtime: 121, genres: ["Drama", "War"],
      directors: ["Hank Delgado"], cast: ["Tom Okafor", "Marcus Vale"], languages: ["English", "German"],
      countries: ["USA", "Germany"], imdb: { rating: 7.8, votes: 143000 }, awards: { wins: 8, nominations: 16 }, budgetM: 68 },
    { _id: 115, title: "Marigold Season", year: 2012, rated: "PG", runtime: 104, genres: ["Romance", "Comedy"],
      directors: ["Mei Chen"], cast: ["Priya Nair", "Liam Vance"], languages: ["Hindi", "English"],
      countries: ["India"], imdb: { rating: 7.0, votes: 39600 }, awards: { wins: 3, nominations: 7 }, budgetM: 6 },
    { _id: 116, title: "The Long Descent", year: 2025, rated: "PG-13", runtime: 137, genres: ["Adventure", "Thriller"],
      directors: ["Nadia Farouk"], cast: ["Ada Blake", "Sofia Ruiz", "Tom Okafor"], languages: ["English"],
      countries: ["USA"], imdb: { rating: 7.3, votes: 9800 }, awards: { wins: 0, nominations: 0 }, budgetM: 88 },
    { _id: 117, title: "Static Bloom", year: 2014, rated: "NC-17", runtime: 110, genres: ["Drama"],
      directors: ["Kenji Mori"], cast: ["Marcus Vale"], languages: ["English"],
      countries: ["USA"], imdb: { rating: 5.9, votes: 7200 }, awards: { wins: 0, nominations: 0 }, budgetM: 4 },
    { _id: 118, title: "Bright Machinery", year: 2010, rated: "PG-13", runtime: 128, genres: ["Sci-Fi", "Drama"],
      directors: ["Ana Roth"], cast: ["Liam Vance", "Tom Okafor", "Ada Blake"], languages: ["English"],
      countries: ["USA", "UK"], imdb: { rating: 8.2, votes: 331000 }, awards: { wins: 11, nominations: 24 }, budgetM: 140 }
  ],

  customers: [
    { _id: "C1", name: "Aarav Sharma", email: "aarav@example.com", city: "Pune", tier: "gold", signupYear: 2019, age: 31, newsletter: true },
    { _id: "C2", name: "Bella Ortiz", email: "bella@example.com", city: "Austin", tier: "silver", signupYear: 2021, age: 27, newsletter: false },
    { _id: "C3", name: "Chen Wei", email: "chen@example.com", city: "Singapore", tier: "gold", signupYear: 2018, age: 44, newsletter: true },
    { _id: "C4", name: "Diana Novak", email: "diana@example.com", city: "Berlin", tier: "bronze", signupYear: 2023, age: 22 },
    { _id: "C5", name: "Emeka Obi", email: "emeka@example.com", city: "Lagos", tier: "silver", signupYear: 2020, age: 38, newsletter: true },
    { _id: "C6", name: "Fatima Zahra", email: "fatima@example.com", city: "Casablanca", tier: "gold", signupYear: 2017, age: 35, newsletter: false },
    { _id: "C7", name: "Grace Lin", email: "grace@example.com", city: "Toronto", tier: "bronze", signupYear: 2022, age: 29, newsletter: true },
    { _id: "C8", name: "Hugo Martins", email: "hugo@example.com", city: "Lisbon", tier: "silver", signupYear: 2024, age: 41 }
  ],

  products: [
    { _id: "P1", sku: "KB-100", name: "Mechanical Keyboard", category: "peripherals", price: 129.0, stock: 42, tags: ["usb", "rgb", "hotswap"] },
    { _id: "P2", sku: "MS-200", name: "Wireless Mouse", category: "peripherals", price: 49.5, stock: 130, tags: ["wireless", "ergonomic"] },
    { _id: "P3", sku: "MN-300", name: "27in 4K Monitor", category: "displays", price: 379.0, stock: 18, tags: ["4k", "ips", "usb-c"] },
    { _id: "P4", sku: "HD-400", name: "Noise Cancelling Headset", category: "audio", price: 219.0, stock: 0, tags: ["wireless", "anc"] },
    { _id: "P5", sku: "DK-500", name: "Standing Desk", category: "furniture", price: 549.0, stock: 7, tags: ["adjustable", "oak"] },
    { _id: "P6", sku: "CH-600", name: "Ergo Chair", category: "furniture", price: 429.0, stock: 25, tags: ["ergonomic", "mesh"] },
    { _id: "P7", sku: "SS-700", name: "1TB NVMe SSD", category: "storage", price: 99.0, stock: 88, tags: ["nvme", "pcie4"] },
    { _id: "P8", sku: "WC-800", name: "1080p Webcam", category: "peripherals", price: 79.0, stock: 3, tags: ["usb", "1080p"] },
    { _id: "P9", sku: "SP-900", name: "Desk Speakers", category: "audio", price: 159.0, stock: 12, tags: ["bluetooth", "stereo"] },
    { _id: "P10", sku: "HB-110", name: "USB-C Hub", category: "peripherals", price: 59.0, stock: 64, tags: ["usb-c", "hdmi", "compact"] }
  ],

  orders: [
    { _id: "O1", customerId: "C1", status: "delivered", channel: "web", date: new Date("2024-01-12"),
      items: [ { sku: "KB-100", qty: 1, price: 129.0 }, { sku: "MS-200", qty: 2, price: 49.5 } ], total: 228.0, coupon: "NEW10" },
    { _id: "O2", customerId: "C2", status: "shipped", channel: "mobile", date: new Date("2024-02-03"),
      items: [ { sku: "MN-300", qty: 1, price: 379.0 } ], total: 379.0 },
    { _id: "O3", customerId: "C1", status: "cancelled", channel: "web", date: new Date("2024-02-19"),
      items: [ { sku: "HD-400", qty: 1, price: 219.0 } ], total: 219.0 },
    { _id: "O4", customerId: "C3", status: "delivered", channel: "store", date: new Date("2024-03-08"),
      items: [ { sku: "DK-500", qty: 1, price: 549.0 }, { sku: "CH-600", qty: 1, price: 429.0 } ], total: 978.0 },
    { _id: "O5", customerId: "C4", status: "pending", channel: "mobile", date: new Date("2024-03-22"),
      items: [ { sku: "SS-700", qty: 3, price: 99.0 } ], total: 297.0, coupon: "BULK5" },
    { _id: "O6", customerId: "C5", status: "delivered", channel: "web", date: new Date("2024-04-01"),
      items: [ { sku: "WC-800", qty: 1, price: 79.0 }, { sku: "HB-110", qty: 2, price: 59.0 } ], total: 197.0 },
    { _id: "O7", customerId: "C3", status: "delivered", channel: "web", date: new Date("2024-04-17"),
      items: [ { sku: "SP-900", qty: 2, price: 159.0 } ], total: 318.0 },
    { _id: "O8", customerId: "C6", status: "shipped", channel: "mobile", date: new Date("2024-05-05"),
      items: [ { sku: "KB-100", qty: 2, price: 129.0 }, { sku: "SS-700", qty: 1, price: 99.0 }, { sku: "MS-200", qty: 1, price: 49.5 } ], total: 406.5 },
    { _id: "O9", customerId: "C2", status: "delivered", channel: "web", date: new Date("2024-05-28"),
      items: [ { sku: "CH-600", qty: 1, price: 429.0 } ], total: 429.0, coupon: "NEW10" },
    { _id: "O10", customerId: "C7", status: "pending", channel: "store", date: new Date("2024-06-11"),
      items: [ { sku: "MN-300", qty: 2, price: 379.0 }, { sku: "HB-110", qty: 1, price: 59.0 } ], total: 817.0 },
    { _id: "O11", customerId: "C5", status: "cancelled", channel: "mobile", date: new Date("2024-06-30"),
      items: [ { sku: "SP-900", qty: 1, price: 159.0 } ], total: 159.0 },
    { _id: "O12", customerId: "C1", status: "delivered", channel: "web", date: new Date("2024-07-14"),
      items: [ { sku: "HD-400", qty: 1, price: 219.0 }, { sku: "WC-800", qty: 3, price: 79.0 } ], total: 456.0 },
    { _id: "O13", customerId: "C8", status: "shipped", channel: "web", date: new Date("2024-08-02"),
      items: [ { sku: "DK-500", qty: 1, price: 549.0 } ], total: 549.0 },
    { _id: "O14", customerId: "C6", status: "delivered", channel: "store", date: new Date("2024-08-21"),
      items: [ { sku: "MS-200", qty: 4, price: 49.5 } ], total: 198.0, coupon: "BULK5" },
    { _id: "O15", customerId: "C3", status: "pending", channel: "web", date: new Date("2024-09-09"),
      items: [ { sku: "SS-700", qty: 2, price: 99.0 }, { sku: "HB-110", qty: 1, price: 59.0 } ], total: 257.0 }
  ],

  employees: [
    { _id: "E1", name: "Root Rajan", title: "CEO", dept: "Exec", salary: 320000, hiredYear: 2011, skills: ["strategy", "finance"] },
    { _id: "E2", name: "Meera Kapoor", title: "VP Engineering", dept: "Engineering", salary: 245000, hiredYear: 2014, reportsTo: "E1", skills: ["architecture", "go", "mongodb"] },
    { _id: "E3", name: "Devon Clarke", title: "VP Sales", dept: "Sales", salary: 210000, hiredYear: 2015, reportsTo: "E1", skills: ["negotiation", "crm"] },
    { _id: "E4", name: "Sana Iqbal", title: "Engineering Manager", dept: "Engineering", salary: 185000, hiredYear: 2017, reportsTo: "E2", skills: ["node", "mongodb", "leadership"] },
    { _id: "E5", name: "Tobias Lang", title: "Senior Engineer", dept: "Engineering", salary: 162000, hiredYear: 2018, reportsTo: "E4", skills: ["react", "node", "graphql"] },
    { _id: "E6", name: "Priyanka Rao", title: "Engineer", dept: "Engineering", salary: 128000, hiredYear: 2021, reportsTo: "E4", skills: ["react", "css"] },
    { _id: "E7", name: "Omar Haddad", title: "Engineer", dept: "Engineering", salary: 121000, hiredYear: 2022, reportsTo: "E4", skills: ["node", "mongodb"] },
    { _id: "E8", name: "Ivy Chen", title: "Account Executive", dept: "Sales", salary: 96000, hiredYear: 2020, reportsTo: "E3", skills: ["crm"] },
    { _id: "E9", name: "Luis Moreno", title: "Account Executive", dept: "Sales", salary: 91000, hiredYear: 2023, reportsTo: "E3", skills: ["crm", "spanish"] },
    { _id: "E10", name: "Hana Sato", title: "Data Analyst", dept: "Analytics", salary: 118000, hiredYear: 2022, reportsTo: "E2", skills: ["sql", "mongodb", "python"] }
  ]
};
